# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Topinup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for FireApp


  pod 'RealmSwift'
#  pod 'Firebase/AdMob' , '6.33.0'
  pod 'Firebase/Messaging' , '6.33.0'
  pod 'Firebase/Database' , '6.33.0'
  pod 'Firebase/Auth' , '6.33.0'
  pod 'Firebase/Storage' , '6.33.0'
  pod 'Firebase/Functions', '6.33.0'
  pod 'FirebaseUI/Phone', '8.5.1'
  pod 'UITextView+Placeholder', '1.4.0'
  pod "SwiftyCam", '4.0.0'
  pod 'BubbleTransition', '4.0.0'
  pod 'LBTATools','1.0.12'
  pod 'UIColor_Hex_Swift', '5.1.0'
  pod 'ImageScrollView', '1.9.1'
  pod 'Hero', '1.5.0'
  pod 'iRecordView' ,'0.1.3'
  pod 'JFContactsPicker', '2.0.0'
  pod "TTCardView", '0.1.1'
  pod 'EnhancedCircleImageView' , '0.1'
  pod 'LocationPicker', '1.4.2'
  pod 'GrowingTextView', '0.7.2'
  pod 'IQKeyboardManagerSwift', '6.5.6'
  pod 'ContextMenu','0.4.0'
  pod 'CircleProgressButton','0.5.1'
  pod 'SwiftEventBus', '5.0.0'
  pod 'libPhoneNumber-iOS', '0.9.15'
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxFirebase/Database', '0.3.8'
  pod 'RxFirebase/Storage', '0.3.8'
  pod 'RxFirebase/Functions', '0.3.8'
  pod 'RxOptional', '4.1.0'
  pod 'CircleProgressView', '1.2.0'
  pod 'Kingfisher', '5.15.5'
  pod 'iOSPhotoEditor', '1.0.0'
  pod 'AgoraRtcEngine_iOS'
  pod 'ALCameraViewController', '3.1'
  pod 'WXImageCompress', '0.1.3'
  pod 'DateTimePicker', '2.4.1'

  pod 'Permission/Photos' , '3.1.2'
  pod 'Permission/Notifications', '3.1.2'
  pod 'Permission/Microphone', '3.1.2'
  pod 'Permission/MediaLibrary', '3.1.2'
  pod 'Permission/Contacts', '3.1.2'
  pod 'Permission/Camera', '3.1.2'

  pod 'BadgeSwift', '8.0.0'
  pod "AlertBar", '0.5.0'
  pod 'NotificationBannerSwift', '3.0.2'
  pod 'NotificationView', '0.2.4'
  pod 'BottomPopup', '0.6.0'
  pod 'PhotoCircleCrop'
  pod 'ZLPhotoBrowser'

#user app
pod 'Alamofire', '~> 4.8.2'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'FSCalendar'
pod 'GoogleMaps'
pod 'GooglePlaces'
#pod 'GooglePlacePicker'
pod 'Cosmos'
pod 'SDWebImage'
pod 'BRYXBanner', '~> 0.8.0'
pod 'SideMenu', '~> 6.0'
pod 'Socket.IO-Client-Swift', '~> 11.1.3'
pod 'ReverseExtension'
pod 'VIMediaCache'
pod 'SVProgressHUD'
#pod 'Firebase/Core'
pod 'YNSearch'
pod 'SwiftPopup'

end

target 'ShareExtension' do
  pod 'RealmSwift'
    pod 'RxSwift', '5.1.1'
    pod 'RxCocoa', '5.1.1'
   
end

target 'NotificationService' do
  pod 'RealmSwift'

  pod 'Firebase/Messaging' , '6.33.0'
  pod 'Firebase/Database' , '6.33.0'
  pod 'Firebase/Auth' , '6.33.0'
  pod 'Firebase/Storage' , '6.33.0'
  pod 'Firebase/Functions', '6.33.0'

  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxFirebase/Database', '0.3.8'
  pod 'RxFirebase/Storage', '0.3.8'
  pod 'RxFirebase/Functions', '0.3.8'
  pod 'RxOptional', '4.1.0'
  pod 'WXImageCompress', '0.1.3'
  pod 'SwiftEventBus', '5.0.0'
  pod 'libPhoneNumber-iOS', '0.9.15'
  pod 'Kingfisher', '5.15.5'

end


